//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.07.29 at 08:18:25 PM BST
//


package net.cgps.wgsa.genotyphi.lib.ncbi;

import javax.xml.bind.annotation.*;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="BlastOutput_program" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="BlastOutput_version" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="BlastOutput_reference" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="BlastOutput_db" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="BlastOutput_query-ID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="BlastOutput_query-def" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="BlastOutput_query-len" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="BlastOutput_query-seq" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BlastOutput_param">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.ncbi.nlm.nih.gov}Parameters"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="BlastOutput_iterations">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element ref="{http://www.ncbi.nlm.nih.gov}Iteration"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="BlastOutput_mbstat" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.ncbi.nlm.nih.gov}Statistics"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "",
    propOrder = {"blastOutputProgram", "blastOutputVersion", "blastOutputReference", "blastOutputDb", "blastOutputQueryID", "blastOutputQueryDef", "blastOutputQueryLen", "blastOutputQuerySeq", "blastOutputParam", "blastOutputIterations", "blastOutputMbstat"})
@XmlRootElement(name = "BlastOutput")
public class BlastOutput {

  @XmlElement(name = "BlastOutput_program", required = true)
  protected String blastOutputProgram;
  @XmlElement(name = "BlastOutput_version", required = true)
  protected String blastOutputVersion;
  @XmlElement(name = "BlastOutput_reference", required = true)
  protected String blastOutputReference;
  @XmlElement(name = "BlastOutput_db", required = true)
  protected String blastOutputDb;
  @XmlElement(name = "BlastOutput_query-ID", required = true)
  protected String blastOutputQueryID;
  @XmlElement(name = "BlastOutput_query-def", required = true)
  protected String blastOutputQueryDef;
  @XmlElement(name = "BlastOutput_query-len", required = true)
  protected BigInteger blastOutputQueryLen;
  @XmlElement(name = "BlastOutput_query-seq")
  protected String blastOutputQuerySeq;
  @XmlElement(name = "BlastOutput_param", required = true)
  protected BlastOutputParam blastOutputParam;
  @XmlElement(name = "BlastOutput_iterations", required = true)
  protected BlastOutputIterations blastOutputIterations;
  @XmlElement(name = "BlastOutput_mbstat")
  protected BlastOutputMbstat blastOutputMbstat;

  /**
   * Gets the value of the blastOutputProgram property.
   *
   * @return possible object is {@link String }
   */
  public String getBlastOutputProgram() {

    return this.blastOutputProgram;
  }

  /**
   * Sets the value of the blastOutputProgram property.
   *
   * @param value
   *     allowed object is {@link String }
   */
  public void setBlastOutputProgram(String value) {

    this.blastOutputProgram = value;
  }

  /**
   * Gets the value of the blastOutputVersion property.
   *
   * @return possible object is {@link String }
   */
  public String getBlastOutputVersion() {

    return this.blastOutputVersion;
  }

  /**
   * Sets the value of the blastOutputVersion property.
   *
   * @param value
   *     allowed object is {@link String }
   */
  public void setBlastOutputVersion(String value) {

    this.blastOutputVersion = value;
  }

  /**
   * Gets the value of the blastOutputReference property.
   *
   * @return possible object is {@link String }
   */
  public String getBlastOutputReference() {

    return this.blastOutputReference;
  }

  /**
   * Sets the value of the blastOutputReference property.
   *
   * @param value
   *     allowed object is {@link String }
   */
  public void setBlastOutputReference(String value) {

    this.blastOutputReference = value;
  }

  /**
   * Gets the value of the blastOutputDb property.
   *
   * @return possible object is {@link String }
   */
  public String getBlastOutputDb() {

    return this.blastOutputDb;
  }

  /**
   * Sets the value of the blastOutputDb property.
   *
   * @param value
   *     allowed object is {@link String }
   */
  public void setBlastOutputDb(String value) {

    this.blastOutputDb = value;
  }

  /**
   * Gets the value of the blastOutputQueryID property.
   *
   * @return possible object is {@link String }
   */
  public String getBlastOutputQueryID() {

    return this.blastOutputQueryID;
  }

  /**
   * Sets the value of the blastOutputQueryID property.
   *
   * @param value
   *     allowed object is {@link String }
   */
  public void setBlastOutputQueryID(String value) {

    this.blastOutputQueryID = value;
  }

  /**
   * Gets the value of the blastOutputQueryDef property.
   *
   * @return possible object is {@link String }
   */
  public String getBlastOutputQueryDef() {

    return this.blastOutputQueryDef;
  }

  /**
   * Sets the value of the blastOutputQueryDef property.
   *
   * @param value
   *     allowed object is {@link String }
   */
  public void setBlastOutputQueryDef(String value) {

    this.blastOutputQueryDef = value;
  }

  /**
   * Gets the value of the blastOutputQueryLen property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getBlastOutputQueryLen() {

    return this.blastOutputQueryLen;
  }

  /**
   * Sets the value of the blastOutputQueryLen property.
   *
   * @param value
   *     allowed object is {@link BigInteger }
   */
  public void setBlastOutputQueryLen(BigInteger value) {

    this.blastOutputQueryLen = value;
  }

  /**
   * Gets the value of the blastOutputQuerySeq property.
   *
   * @return possible object is {@link String }
   */
  public String getBlastOutputQuerySeq() {

    return this.blastOutputQuerySeq;
  }

  /**
   * Sets the value of the blastOutputQuerySeq property.
   *
   * @param value
   *     allowed object is {@link String }
   */
  public void setBlastOutputQuerySeq(String value) {

    this.blastOutputQuerySeq = value;
  }

  /**
   * Gets the value of the blastOutputParam property.
   *
   * @return possible object is {@link BlastOutputParam }
   */
  public BlastOutputParam getBlastOutputParam() {

    return this.blastOutputParam;
  }

  /**
   * Sets the value of the blastOutputParam property.
   *
   * @param value
   *     allowed object is {@link BlastOutputParam }
   */
  public void setBlastOutputParam(BlastOutputParam value) {

    this.blastOutputParam = value;
  }

  /**
   * Gets the value of the blastOutputIterations property.
   *
   * @return possible object is {@link BlastOutputIterations }
   */
  public BlastOutputIterations getBlastOutputIterations() {

    return this.blastOutputIterations;
  }

  /**
   * Sets the value of the blastOutputIterations property.
   *
   * @param value
   *     allowed object is {@link BlastOutputIterations }
   */
  public void setBlastOutputIterations(BlastOutputIterations value) {

    this.blastOutputIterations = value;
  }

  /**
   * Gets the value of the blastOutputMbstat property.
   *
   * @return possible object is {@link BlastOutputMbstat }
   */
  public BlastOutputMbstat getBlastOutputMbstat() {

    return this.blastOutputMbstat;
  }

  /**
   * Sets the value of the blastOutputMbstat property.
   *
   * @param value
   *     allowed object is {@link BlastOutputMbstat }
   */
  public void setBlastOutputMbstat(BlastOutputMbstat value) {

    this.blastOutputMbstat = value;
  }

  @Override
  public String toString() {

    return "BlastOutput{" +
        "blastOutputProgram='" + this.blastOutputProgram + '\'' +
        ", blastOutputVersion='" + this.blastOutputVersion + '\'' +
        ", blastOutputReference='" + this.blastOutputReference + '\'' +
        ", blastOutputDb='" + this.blastOutputDb + '\'' +
        ", blastOutputQueryID='" + this.blastOutputQueryID + '\'' +
        ", blastOutputQueryDef='" + this.blastOutputQueryDef + '\'' +
        ", blastOutputQueryLen=" + this.blastOutputQueryLen +
        ", blastOutputQuerySeq='" + this.blastOutputQuerySeq + '\'' +
        ", blastOutputParam=" + this.blastOutputParam +
        ", blastOutputIterations=" + this.blastOutputIterations +
        ", blastOutputMbstat=" + this.blastOutputMbstat +
        '}';
  }


  /**
   * <p>Java class for anonymous complex type.
   * <p/>
   * <p>The following schema fragment specifies the expected content contained within this class.
   * <p/>
   * <pre>
   * &lt;complexType>
   *   &lt;complexContent>
   *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
   *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
   *         &lt;element ref="{http://www.ncbi.nlm.nih.gov}Iteration"/>
   *       &lt;/sequence>
   *     &lt;/restriction>
   *   &lt;/complexContent>
   * &lt;/complexType>
   * </pre>
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "", propOrder = {"iteration"})
  public static class BlastOutputIterations {

    @XmlElement(name = "Iteration")
    protected List<Iteration> iteration;

    /**
     * Gets the value of the iteration property.
     * <p/>
     * <p/>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
     * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
     * the iteration property.
     * <p/>
     * <p/>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIteration().add(newItem);
     * </pre>
     * <p/>
     * <p/>
     * <p/>
     * Objects of the following type(s) are allowed in the list {@link Iteration }
     */
    public List<Iteration> getIteration() {

      if (this.iteration == null) {
        this.iteration = new ArrayList<>();
      }
      return this.iteration;
    }

  }


  /**
   * <p>Java class for anonymous complex type.
   * <p/>
   * <p>The following schema fragment specifies the expected content contained within this class.
   * <p/>
   * <pre>
   * &lt;complexType>
   *   &lt;complexContent>
   *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
   *       &lt;sequence>
   *         &lt;element ref="{http://www.ncbi.nlm.nih.gov}Statistics"/>
   *       &lt;/sequence>
   *     &lt;/restriction>
   *   &lt;/complexContent>
   * &lt;/complexType>
   * </pre>
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "", propOrder = {"statistics"})
  public static class BlastOutputMbstat {

    @XmlElement(name = "Statistics", required = true)
    protected Statistics statistics;

    /**
     * Gets the value of the statistics property.
     *
     * @return possible object is {@link Statistics }
     */
    public Statistics getStatistics() {

      return this.statistics;
    }

    /**
     * Sets the value of the statistics property.
     *
     * @param value
     *     allowed object is {@link Statistics }
     */
    public void setStatistics(Statistics value) {

      this.statistics = value;
    }

  }


  /**
   * <p>Java class for anonymous complex type.
   * <p/>
   * <p>The following schema fragment specifies the expected content contained within this class.
   * <p/>
   * <pre>
   * &lt;complexType>
   *   &lt;complexContent>
   *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
   *       &lt;sequence>
   *         &lt;element ref="{http://www.ncbi.nlm.nih.gov}Parameters"/>
   *       &lt;/sequence>
   *     &lt;/restriction>
   *   &lt;/complexContent>
   * &lt;/complexType>
   * </pre>
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "", propOrder = {"parameters"})
  public static class BlastOutputParam {

    @XmlElement(name = "Parameters", required = true)
    protected Parameters parameters;

    /**
     * Gets the value of the parameters property.
     *
     * @return possible object is {@link Parameters }
     */
    public Parameters getParameters() {

      return this.parameters;
    }

    /**
     * Sets the value of the parameters property.
     *
     * @param value
     *     allowed object is {@link Parameters }
     */
    public void setParameters(Parameters value) {

      this.parameters = value;
    }

  }

}
