//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.07.29 at 08:18:25 PM BST
//


package net.cgps.wgsa.genotyphi.lib.ncbi;

import javax.xml.bind.annotation.*;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Hit_num" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="Hit_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Hit_def" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Hit_accession" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Hit_len" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="Hit_hsps" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element ref="{http://www.ncbi.nlm.nih.gov}Hsp"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "hitNum",
    "hitId",
    "hitDef",
    "hitAccession",
    "hitLen",
    "hitHsps"
})
@XmlRootElement(name = "Hit")
public class Hit {

  @XmlElement(name = "Hit_num", required = true)
  protected BigInteger hitNum;
  @XmlElement(name = "Hit_id", required = true)
  protected String hitId;
  @XmlElement(name = "Hit_def", required = true)
  protected String hitDef;
  @XmlElement(name = "Hit_accession", required = true)
  protected String hitAccession;
  @XmlElement(name = "Hit_len", required = true)
  protected BigInteger hitLen;
  @XmlElement(name = "Hit_hsps")
  protected HitHsps hitHsps;

  /**
   * Gets the value of the hitNum property.
   *
   * @return possible object is
   * {@link BigInteger }
   */
  public BigInteger getHitNum() {

    return this.hitNum;
  }

  /**
   * Sets the value of the hitNum property.
   *
   * @param value
   *     allowed object is
   *     {@link BigInteger }
   */
  public void setHitNum(BigInteger value) {

    this.hitNum = value;
  }

  /**
   * Gets the value of the hitId property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getHitId() {

    return this.hitId;
  }

  /**
   * Sets the value of the hitId property.
   *
   * @param value
   *     allowed object is
   *     {@link String }
   */
  public void setHitId(String value) {

    this.hitId = value;
  }

  /**
   * Gets the value of the hitDef property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getHitDef() {

    return this.hitDef;
  }

  /**
   * Sets the value of the hitDef property.
   *
   * @param value
   *     allowed object is
   *     {@link String }
   */
  public void setHitDef(String value) {

    this.hitDef = value;
  }

  /**
   * Gets the value of the hitAccession property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getHitAccession() {

    return this.hitAccession;
  }

  /**
   * Sets the value of the hitAccession property.
   *
   * @param value
   *     allowed object is
   *     {@link String }
   */
  public void setHitAccession(String value) {

    this.hitAccession = value;
  }

  /**
   * Gets the value of the hitLen property.
   *
   * @return possible object is
   * {@link BigInteger }
   */
  public BigInteger getHitLen() {

    return this.hitLen;
  }

  /**
   * Sets the value of the hitLen property.
   *
   * @param value
   *     allowed object is
   *     {@link BigInteger }
   */
  public void setHitLen(BigInteger value) {

    this.hitLen = value;
  }

  /**
   * Gets the value of the hitHsps property.
   *
   * @return possible object is
   * {@link HitHsps }
   */
  public HitHsps getHitHsps() {

    return this.hitHsps;
  }

  /**
   * Sets the value of the hitHsps property.
   *
   * @param value
   *     allowed object is
   *     {@link HitHsps }
   */
  public void setHitHsps(HitHsps value) {

    this.hitHsps = value;
  }


  /**
   * <p>Java class for anonymous complex type.
   * <p/>
   * <p>The following schema fragment specifies the expected content contained within this class.
   * <p/>
   * <pre>
   * &lt;complexType>
   *   &lt;complexContent>
   *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
   *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
   *         &lt;element ref="{http://www.ncbi.nlm.nih.gov}Hsp"/>
   *       &lt;/sequence>
   *     &lt;/restriction>
   *   &lt;/complexContent>
   * &lt;/complexType>
   * </pre>
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "", propOrder = {
      "hsp"
  })
  public static class HitHsps {

    @XmlElement(name = "Hsp")
    protected List<Hsp> hsp;

    /**
     * Gets the value of the hsp property.
     * <p/>
     * <p/>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the hsp property.
     * <p/>
     * <p/>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHsp().add(newItem);
     * </pre>
     * <p/>
     * <p/>
     * <p/>
     * Objects of the following type(s) are allowed in the list
     * {@link Hsp }
     */
    public List<Hsp> getHsp() {

      if (this.hsp == null) {
        this.hsp = new ArrayList<>();
      }
      return this.hsp;
    }

  }

}
