//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.07.29 at 08:18:25 PM BST
//


package net.cgps.wgsa.genotyphi.lib.ncbi;

import javax.xml.bind.annotation.*;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Iteration_iter-num" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="Iteration_query-ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Iteration_query-def" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Iteration_query-len" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="Iteration_hits" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element ref="{http://www.ncbi.nlm.nih.gov}Hit"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Iteration_stat" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.ncbi.nlm.nih.gov}Statistics"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Iteration_message" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "iterationIterNum",
    "iterationQueryID",
    "iterationQueryDef",
    "iterationQueryLen",
    "iterationHits",
    "iterationStat",
    "iterationMessage"
})
@XmlRootElement(name = "Iteration")
public class Iteration {

  @XmlElement(name = "Iteration_iter-num", required = true)
  protected BigInteger iterationIterNum;
  @XmlElement(name = "Iteration_query-ID")
  protected String iterationQueryID;
  @XmlElement(name = "Iteration_query-def")
  protected String iterationQueryDef;
  @XmlElement(name = "Iteration_query-len")
  protected BigInteger iterationQueryLen;
  @XmlElement(name = "Iteration_hits")
  protected IterationHits iterationHits;
  @XmlElement(name = "Iteration_stat")
  protected IterationStat iterationStat;
  @XmlElement(name = "Iteration_message")
  protected String iterationMessage;

  /**
   * Gets the value of the iterationIterNum property.
   *
   * @return possible object is
   * {@link BigInteger }
   */
  public BigInteger getIterationIterNum() {

    return this.iterationIterNum;
  }

  /**
   * Sets the value of the iterationIterNum property.
   *
   * @param value
   *     allowed object is
   *     {@link BigInteger }
   */
  public void setIterationIterNum(BigInteger value) {

    this.iterationIterNum = value;
  }

  /**
   * Gets the value of the iterationQueryID property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getIterationQueryID() {

    return this.iterationQueryID;
  }

  /**
   * Sets the value of the iterationQueryID property.
   *
   * @param value
   *     allowed object is
   *     {@link String }
   */
  public void setIterationQueryID(String value) {

    this.iterationQueryID = value;
  }

  /**
   * Gets the value of the iterationQueryDef property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getIterationQueryDef() {

    return this.iterationQueryDef;
  }

  /**
   * Sets the value of the iterationQueryDef property.
   *
   * @param value
   *     allowed object is
   *     {@link String }
   */
  public void setIterationQueryDef(String value) {

    this.iterationQueryDef = value;
  }

  /**
   * Gets the value of the iterationQueryLen property.
   *
   * @return possible object is
   * {@link BigInteger }
   */
  public BigInteger getIterationQueryLen() {

    return this.iterationQueryLen;
  }

  /**
   * Sets the value of the iterationQueryLen property.
   *
   * @param value
   *     allowed object is
   *     {@link BigInteger }
   */
  public void setIterationQueryLen(BigInteger value) {

    this.iterationQueryLen = value;
  }

  /**
   * Gets the value of the iterationHits property.
   *
   * @return possible object is
   * {@link IterationHits }
   */
  public IterationHits getIterationHits() {

    return this.iterationHits;
  }

  /**
   * Sets the value of the iterationHits property.
   *
   * @param value
   *     allowed object is
   *     {@link IterationHits }
   */
  public void setIterationHits(IterationHits value) {

    this.iterationHits = value;
  }

  /**
   * Gets the value of the iterationStat property.
   *
   * @return possible object is
   * {@link IterationStat }
   */
  public IterationStat getIterationStat() {

    return this.iterationStat;
  }

  /**
   * Sets the value of the iterationStat property.
   *
   * @param value
   *     allowed object is
   *     {@link IterationStat }
   */
  public void setIterationStat(IterationStat value) {

    this.iterationStat = value;
  }

  /**
   * Gets the value of the iterationMessage property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getIterationMessage() {

    return this.iterationMessage;
  }

  /**
   * Sets the value of the iterationMessage property.
   *
   * @param value
   *     allowed object is
   *     {@link String }
   */
  public void setIterationMessage(String value) {

    this.iterationMessage = value;
  }


  /**
   * <p>Java class for anonymous complex type.
   * <p/>
   * <p>The following schema fragment specifies the expected content contained within this class.
   * <p/>
   * <pre>
   * &lt;complexType>
   *   &lt;complexContent>
   *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
   *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
   *         &lt;element ref="{http://www.ncbi.nlm.nih.gov}Hit"/>
   *       &lt;/sequence>
   *     &lt;/restriction>
   *   &lt;/complexContent>
   * &lt;/complexType>
   * </pre>
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "", propOrder = {
      "hit"
  })
  public static class IterationHits {

    @XmlElement(name = "Hit")
    protected List<Hit> hit;

    /**
     * Gets the value of the hit property.
     * <p/>
     * <p/>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the hit property.
     * <p/>
     * <p/>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHit().add(newItem);
     * </pre>
     * <p/>
     * <p/>
     * <p/>
     * Objects of the following type(s) are allowed in the list
     * {@link Hit }
     */
    public List<Hit> getHit() {

      if (this.hit == null) {
        this.hit = new ArrayList<>();
      }
      return this.hit;
    }

  }


  /**
   * <p>Java class for anonymous complex type.
   * <p/>
   * <p>The following schema fragment specifies the expected content contained within this class.
   * <p/>
   * <pre>
   * &lt;complexType>
   *   &lt;complexContent>
   *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
   *       &lt;sequence>
   *         &lt;element ref="{http://www.ncbi.nlm.nih.gov}Statistics"/>
   *       &lt;/sequence>
   *     &lt;/restriction>
   *   &lt;/complexContent>
   * &lt;/complexType>
   * </pre>
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "", propOrder = {
      "statistics"
  })
  public static class IterationStat {

    @XmlElement(name = "Statistics", required = true)
    protected Statistics statistics;

    /**
     * Gets the value of the statistics property.
     *
     * @return possible object is
     * {@link Statistics }
     */
    public Statistics getStatistics() {

      return this.statistics;
    }

    /**
     * Sets the value of the statistics property.
     *
     * @param value
     *     allowed object is
     *     {@link Statistics }
     */
    public void setStatistics(Statistics value) {

      this.statistics = value;
    }

  }

}
